apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    f5nr: "true"
  name: extended-spec-config
  namespace: kube-system
data:
  extendedSpec: |
    mode: default
    externalClustersConfig:
    - clusterName: cluster-1
      secret: default/kubeconfig-1
    - clusterName: cluster-2
      secret: default/kubeconfig-2
    - clusterName: cluster-3
      secret: default/kubeconfig-3