apiVersion: cis.f5.com/v1
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: ts-hello
  namespace: default
spec:
  virtualServerAddress: "10.192.75.121"
  virtualServerPort: 80
  snat: auto
  mode: standard
  pool:
    multiClusterServices:
    - clusterName: cluster-1
      namespace: default
      service: hello-world-app
      servicePort: 8080
      weight: 50
    - clusterName: cluster-2
      namespace: default
      service: hello-world-app
      servicePort: 8080
      weight: 50
  
