apiVersion: cis.f5.com/v1
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: cr-transport-server
  namespace: default
spec:
  virtualServerAddress: "10.192.75.121"
  virtualServerPort: 80
  snat: auto
  mode: standard
  pool:
    multiClusterServices:
    # CIS supports to refer svs from local cluster
      - clusterName: cluster1
        namespace: default
        service: hello-world-app
        servicePort: 8080
        weight: 50
      - clusterName: cluster2
        namespace: default
        service: hello-world-app
        servicePort: 8080
        weight: 50
    monitor:
      interval: 10
      timeout: 31
      type: tcp
  
