apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    f5nr: "true"
  name: extended-spec-config
  namespace: kube-system
data:
  extendedSpec: |
    mode: default
    highAvailabilityCIS:
      primaryEndPoint: http://10.192.125.122/
      probeInterval: 30
      retryInterval: 3
      primaryCluster:
        clusterName: cluster-1
        secret: default/kubeconfig-1
      secondaryCluster:
        clusterName: cluster-2
        secret: default/kubeconfig-2
    externalClustersConfig:
    - clusterName: cluster-3
      secret: default/kubeconfig-3