apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: vs-hello
  namespace: default
spec:
  virtualServerAddress: 10.192.125.123
  virtualServerHTTPPort: 80
  pools:
    - path: /
      multiClusterServices:
        - clusterName: cluster-1
          namespace: default
          service: hello-world-app
          servicePort: 8080
          weight: 50
        - clusterName: cluster-2
          namespace: default
          service: hello-world-app
          servicePort: 8080
          weight: 50
        - clusterName: cluster-3
          namespace: default
          service: hello-world-app
          servicePort: 8080
          weight: 50
      monitor:
        interval: 30
        timeout: 10
        type: http
        send: GET /health HTTP/1.0

    
    
  

