apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: serviceOne-virtual-server
  namespace: services
spec:
  host: services.example.com
  virtualServerAddress: 10.8.0.4
  tlsProfileName: tls-tls1.3
  pools:
    - path: /serviceOne
      multiClusterServices:
      - clusterName: cluster1
        namespace: serviceOne
        service: router-internal-default
        servicePort: 443
        weight: 30
      - clusterName: cluster2
        namespace: serviceOne
        service: router-internal-default
        servicePort: 443
        weight: 30
      - clusterName: cluster3
        namespace: serviceOne
        service: router-internal-default
        servicePort: 443
        weight: 30
      - clusterName: cluster4
        namespace: serviceOne
        service: router-internal-default
        servicePort: 443
        weight: 30
      - path: /servicetwo
      multiClusterServices:
      - clusterName: cluster1
        namespace: servicetwo
        service: router-internal-default
        servicePort: 443
        weight: 30
      - clusterName: cluster2
        namespace: servicetwo
        service: router-internal-default
        servicePort: 443
        weight: 30
      - clusterName: cluster3
        namespace: servicetwo
        service: router-internal-default
        servicePort: 443
        weight: 30
      - clusterName: cluster4
        namespace: servicetwo
        service: router-internal-default
        servicePort: 443
        weight: 30

