apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: tea-virtual-server-edge
  namespace: default
spec:
  host: cafe.example.com
  virtualServerAddress: 10.8.0.4
  tlsProfileName: tlscipher-tls1.3
  httpTraffic: redirect
  pools:
    - path: /login
      multiClusterServices:
      - clusterName: cluster1
        namespace: default
        service: svc-11-external-service
        servicePort: 80
        weight: 30
      - clusterName: cluster2
        namespace: default
        service: svc-22-external-service
        servicePort: 80
        weight: 30
    - path: /coffee
      multiClusterServices:
      - clusterName: cluster3
        namespace: default
        service: svc-1-external-service
        servicePort: 80
        weight: 30
      - clusterName: cluster4
        namespace: default
        service: svc-1-external-service
        servicePort: 80
        weight: 40
    - path: /tea
      multiClusterServices:
      - clusterName: cluster1
        namespace: default
        service: svc-12-external-service
        servicePort: 80
        weight: 30
      - clusterName: cluster2
        namespace: default
        service: svc-21-external-service
        servicePort: 80
        weight: 30